apiVersion: v1
appVersion: "1.0.13"
version: 1.0.13
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via Netcup
name: cert-manager-webhook-netcup
home: https://github.com/aellwein/cert-manager-webhook-netcup
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - netcup
  - ACME
  - DNS01
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alex Ellwein
      email: alex.ellwein@gmail.com
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: added
      description: "bump dependencies"
    - kind: fixed
      description: "upgrade golang.org/x/net to 0.7.0 to mitigate CVE-2022-41723"
  artifacthub.io/signKey: |
    fingerprint: "F91914CE96676E209A8240290EEF2777053A7D1A"
    url: https://keybase.io/aellwein/pgp_keys.asc
